use crate::fields::FieldInterpretation;
use crate::model::ProtocolModel;

fn field_name(index: usize, field: &FieldInterpretation) -> String {
    match field {
        FieldInterpretation::Constant { .. } => {
            if index == 0 {
                "header".to_string()
            } else {
                format!("reserved_{}", index - 1)
            }
        }

        FieldInterpretation::CounterLike { .. } => {
            if index == 0 {
                "counter".to_string()
            } else {
                format!("counter_{}", index)
            }
        }

        _ => format!("field_{}", index),
    }
}

fn best_unique_multi_byte(
    model: &ProtocolModel,
) -> Option<&crate::fields::MultiByteInterpretation> {
    if model.multi_byte_fields.is_empty() {
        return None;
    }

    let best_score = model
        .multi_byte_fields
        .iter()
        .map(|field| field.score)
        .max()?;

    let best: Vec<_> = model
        .multi_byte_fields
        .iter()
        .filter(|field| field.score == best_score)
        .collect();

    if best.len() == 1 { Some(best[0]) } else { None }
}
fn multi_byte_type(kind: &str) -> Option<&'static str> {
    match kind {
        "U16LittleEndian" | "U16BigEndian" => Some("u16"),

        "U32LittleEndian" | "U32BigEndian" => Some("u32"),

        _ => None,
    }
}

fn multi_byte_expression(kind: &str, start: usize) -> Option<String> {
    match kind {
        "U16LittleEndian" => Some(format!(
            "u16::from_le_bytes([frame[{}], frame[{}]])",
            start,
            start + 1
        )),

        "U16BigEndian" => Some(format!(
            "u16::from_be_bytes([frame[{}], frame[{}]])",
            start,
            start + 1
        )),

        "U32LittleEndian" => Some(format!(
            "u32::from_le_bytes([frame[{}], frame[{}], frame[{}], frame[{}]])",
            start,
            start + 1,
            start + 2,
            start + 3
        )),

        "U32BigEndian" => Some(format!(
            "u32::from_be_bytes([frame[{}], frame[{}], frame[{}], frame[{}]])",
            start,
            start + 1,
            start + 2,
            start + 3
        )),

        _ => None,
    }
}

fn unique_field_name(base: String, used: &mut Vec<String>) -> String {
    if !used.contains(&base) {
        used.push(base.clone());
        return base;
    }

    let mut suffix = 2;

    loop {
        let candidate = format!("{}_{}", base, suffix);

        if !used.contains(&candidate) {
            used.push(candidate.clone());
            return candidate;
        }

        suffix += 1;
    }
}

// ------------------------------------------------------------
// Parse "prefix [01, 02]" from ProtocolModel's display string
// ------------------------------------------------------------

fn parse_prefix_string(kind: &str) -> Option<Vec<u8>> {
    let rest = kind.strip_prefix("prefix [")?;
    let rest = rest.strip_suffix(']')?;

    if rest.trim().is_empty() {
        return Some(Vec::new());
    }

    rest.split(',')
        .map(|part| u8::from_str_radix(part.trim(), 16).ok())
        .collect()
}

// ------------------------------------------------------------
// Generate length-field validation
// ------------------------------------------------------------

fn generate_length_validation(
    out: &mut String,
    length_offset: usize,
    payload_offset: usize,
    checksum_width: usize,
) {
    out.push_str("    // Length-based framing validation\n");

    out.push_str(&format!("    if frame.len() <= {} {{\n", length_offset));

    out.push_str("        return Err(\"invalid frame length\");\n");
    out.push_str("    }\n\n");

    out.push_str(&format!(
        "    let payload_length = frame[{}] as usize;\n",
        length_offset
    ));

    out.push_str(&format!(
        "    let expected_length = {} + payload_length + {};\n",
        payload_offset, checksum_width
    ));

    out.push_str("    if frame.len() != expected_length {\n");
    out.push_str("        return Err(\"invalid frame length\");\n");
    out.push_str("    }\n\n");
}

// ------------------------------------------------------------
// Generate fixed-length validation
// ------------------------------------------------------------

fn generate_fixed_length_validation(out: &mut String, required_length: usize) {
    out.push_str(&format!("    if frame.len() != {} {{\n", required_length));

    out.push_str("        return Err(\"invalid frame length\");\n");
    out.push_str("    }\n\n");
}

// ------------------------------------------------------------
// Main Rust generator
// ------------------------------------------------------------

pub fn generate_rust(model: &ProtocolModel, frames: &[Vec<u8>]) -> String {
    let mut out = String::new();

    out.push_str("// Generated by Babelfish\n");
    out.push_str("// WARNING: Review all ambiguous interpretations before production use.\n\n");

    let unique_multi_byte = best_unique_multi_byte(model);

    // ------------------------------------------------------------
    // Packet struct
    // ------------------------------------------------------------

    out.push_str("#[derive(Debug)]\n");
    out.push_str("pub struct Packet {\n");

    let mut struct_names = Vec::new();

    for (index, field) in model.fields.iter().enumerate() {
        let position = model.checksum.coverage_start + index;

        if let Some(multi) = unique_multi_byte {
            if multi.start == position {
                if let Some(rust_type) = multi_byte_type(&multi.kind) {
                    let base_name = format!("value_{}", multi.start);

                    let name = unique_field_name(base_name, &mut struct_names);

                    out.push_str(&format!("    pub {}: {},\n", name, rust_type));

                    continue;
                }
            }

            if position > multi.start && position < multi.start + multi.width {
                continue;
            }
        }

        let name = unique_field_name(field_name(index, field), &mut struct_names);

        out.push_str(&format!("    pub {}: u8,\n", name));
    }

    out.push_str("}\n\n");

    // ------------------------------------------------------------
    // CRC8
    // ------------------------------------------------------------

    if model.checksum.algorithm == "CRC8" {
        out.push_str(
            r#"fn crc8(data: &[u8]) -> u8 {
    let mut crc = 0u8;

    for &byte in data {
        crc ^= byte;

        for _ in 0..8 {
            if crc & 0x80 != 0 {
                crc = (crc << 1) ^ 0x07;
            } else {
                crc <<= 1;
            }
        }
    }

    crc
}

"#,
        );
    }

    // ------------------------------------------------------------
    // CRC16/MODBUS
    // ------------------------------------------------------------

    if model.checksum.algorithm == "CRC16/MODBUS" {
        out.push_str(
            r#"fn crc16_modbus(data: &[u8]) -> u16 {
    let mut crc: u16 = 0xFFFF;

    for &byte in data {
        crc ^= byte as u16;

        for _ in 0..8 {
            if crc & 1 != 0 {
                crc = (crc >> 1) ^ 0xA001;
            } else {
                crc >>= 1;
            }
        }
    }

    crc
}

"#,
        );
    }

    // ------------------------------------------------------------
    // Parser
    // ------------------------------------------------------------

    out.push_str("pub fn parse_frame(frame: &[u8]) -> Result<Packet, &'static str> {\n");

    // ------------------------------------------------------------
    // Framing validation
    // ------------------------------------------------------------

    out.push_str(&format!(
        "    // Detected framing: {}\n",
        model.framing.kind
    ));

    match (model.framing.length_offset, model.framing.payload_offset) {
        (Some(length_offset), Some(payload_offset)) => {
            generate_length_validation(
                &mut out,
                length_offset,
                payload_offset,
                model.framing.checksum_width,
            );
        }

        (None, None) => {
            let required_length = model.checksum.checksum_end.max(model.checksum.coverage_end);

            generate_fixed_length_validation(&mut out, required_length);

            // Prefix validation is only needed for actual prefix framing.
            if model.framing.kind.starts_with("prefix [") {
                if let Some(prefix) = parse_prefix_string(&model.framing.kind) {
                    if !prefix.is_empty() {
                        out.push_str("    // Prefix validation\n");

                        for (index, byte) in prefix.iter().enumerate() {
                            out.push_str(&format!(
                                "    if frame[{}] != 0x{:02X} {{\n",
                                index, byte
                            ));

                            out.push_str("        return Err(\"invalid frame prefix\");\n");

                            out.push_str("    }\n");
                        }

                        out.push('\n');
                    }
                }
            }
        }

        _ => {
            out.push_str("    return Err(\"invalid framing configuration\");\n\n");
        }
    }
    // ------------------------------------------------------------
    // Checksum information
    // ------------------------------------------------------------

    out.push_str(&format!(
        "    // Detected checksum: {}\n",
        model.checksum.algorithm
    ));

    out.push_str(&format!(
        "    // Coverage: bytes[{}..{}]\n",
        model.checksum.coverage_start, model.checksum.coverage_end
    ));

    out.push_str(&format!(
        "    // Checksum: bytes[{}..{}]\n\n",
        model.checksum.checksum_start, model.checksum.checksum_end
    ));

    // ------------------------------------------------------------
    // CRC8 validation
    // ------------------------------------------------------------

    if model.checksum.algorithm == "CRC8" {
        out.push_str(&format!(
            "    let expected_crc = crc8(&frame[{}..{}]);\n",
            model.checksum.coverage_start, model.checksum.coverage_end
        ));

        out.push_str(&format!(
            "    if frame[{}] != expected_crc {{\n",
            model.checksum.checksum_start
        ));

        out.push_str("        return Err(\"CRC8 validation failed\");\n");

        out.push_str("    }\n\n");
    }

    // ------------------------------------------------------------
    // CRC16/MODBUS validation
    // ------------------------------------------------------------

    if model.checksum.algorithm == "CRC16/MODBUS" {
        let start = model.checksum.checksum_start;

        out.push_str(&format!(
            "    let expected_crc = crc16_modbus(&frame[{}..{}]);\n",
            model.checksum.coverage_start, model.checksum.coverage_end
        ));

        out.push_str(&format!(
            "    let actual_crc = u16::from_le_bytes([frame[{}], frame[{}]]);\n",
            start,
            start + 1
        ));

        out.push_str("    if actual_crc != expected_crc {\n");

        out.push_str("        return Err(\"CRC16/MODBUS validation failed\");\n");

        out.push_str("    }\n\n");
    }

    // ------------------------------------------------------------
    // Field extraction
    // ------------------------------------------------------------

    let mut generated_names = Vec::new();

    for (index, field) in model.fields.iter().enumerate() {
        let position = model.checksum.coverage_start + index;

        if let Some(multi) = unique_multi_byte {
            if multi.start == position {
                if let (Some(_rust_type), Some(expression)) = (
                    multi_byte_type(&multi.kind),
                    multi_byte_expression(&multi.kind, multi.start),
                ) {
                    let base_name = format!("value_{}", multi.start);

                    let name = unique_field_name(base_name, &mut generated_names);

                    out.push_str(&format!("    let {} = {};\n", name, expression));

                    continue;
                }
            }

            if position > multi.start && position < multi.start + multi.width {
                continue;
            }
        }

        let base_name = field_name(index, field);

        let name = unique_field_name(base_name, &mut generated_names);

        out.push_str(&format!("    let {} = frame[{}];\n", name, position));
    }

    // ------------------------------------------------------------
    // Return Packet
    // ------------------------------------------------------------

    out.push_str("\n    Ok(Packet {\n");

    for name in &generated_names {
        out.push_str(&format!("        {},\n", name));
    }

    out.push_str("    })\n");
    out.push_str("}\n");

    // ------------------------------------------------------------
    // Ambiguity information
    // ------------------------------------------------------------

    if unique_multi_byte.is_none() && model.multi_byte_fields.len() > 1 {
        out.push_str(
            r#"

// WARNING: Protocol interpretation is ambiguous.
//
// Babelfish found competing multi-byte interpretations
// with equal evidence. Do not select one without additional
// protocol evidence.
//
// Candidates:
"#,
        );

        for field in &model.multi_byte_fields {
            out.push_str(&format!(
                "//   bytes[{}..{}] -> {:?}, score {:.2}\n",
                field.start,
                field.start + field.width,
                field.kind,
                field.score
            ));
        }

        out.push_str(
            r#"//
// No multi-byte candidate was selected because
// the evidence does not uniquely determine one.
"#,
        );
    }

    // ------------------------------------------------------------
    // Generated tests
    // ------------------------------------------------------------

    if let Some(frame) = frames.first() {
        out.push_str(
            r#"

#[cfg(test)]
mod tests {
    use super::*;

"#,
        );

        // --------------------------------------------------------
        // Test: real captured frame
        // --------------------------------------------------------

        out.push_str("    #[test]\n");
        out.push_str("    fn parses_real_frame() {\n");

        out.push_str("        let frame = [");

        for (index, byte) in frame.iter().enumerate() {
            if index > 0 {
                out.push_str(", ");
            }

            out.push_str(&format!("0x{:02X}", byte));
        }

        out.push_str(
            r#"];

        let packet = parse_frame(&frame)
            .expect("real captured frame should parse");

"#,
        );

        let mut assertion_names = Vec::new();

        for (index, field) in model.fields.iter().enumerate() {
            let position = model.checksum.coverage_start + index;

            if let Some(multi) = unique_multi_byte {
                if multi.start == position {
                    if multi_byte_type(&multi.kind).is_some() {
                        let base_name = format!("value_{}", multi.start);

                        let name = unique_field_name(base_name, &mut assertion_names);

                        if multi.width == 2 && multi.start + 1 < frame.len() {
                            let expected = match multi.kind.as_str() {
                                "U16LittleEndian" => {
                                    u16::from_le_bytes([frame[multi.start], frame[multi.start + 1]])
                                }

                                "U16BigEndian" => {
                                    u16::from_be_bytes([frame[multi.start], frame[multi.start + 1]])
                                }

                                _ => 0,
                            };

                            out.push_str(&format!(
                                "        assert_eq!(packet.{}, 0x{:04X});\n",
                                name, expected
                            ));
                        } else if multi.width == 4 && multi.start + 3 < frame.len() {
                            let expected = match multi.kind.as_str() {
                                "U32LittleEndian" => u32::from_le_bytes([
                                    frame[multi.start],
                                    frame[multi.start + 1],
                                    frame[multi.start + 2],
                                    frame[multi.start + 3],
                                ]),

                                "U32BigEndian" => u32::from_be_bytes([
                                    frame[multi.start],
                                    frame[multi.start + 1],
                                    frame[multi.start + 2],
                                    frame[multi.start + 3],
                                ]),

                                _ => 0,
                            };

                            out.push_str(&format!(
                                "        assert_eq!(packet.{}, 0x{:08X});\n",
                                name, expected
                            ));
                        }

                        continue;
                    }
                }

                if position > multi.start && position < multi.start + multi.width {
                    continue;
                }
            }

            let base_name = field_name(index, field);

            let name = unique_field_name(base_name, &mut assertion_names);

            if position < frame.len() {
                out.push_str(&format!(
                    "        assert_eq!(packet.{}, 0x{:02X});\n",
                    name, frame[position]
                ));
            }
        }

        out.push_str(
            r#"    }

"#,
        );

        // --------------------------------------------------------
        // Test: bad checksum
        // --------------------------------------------------------

        out.push_str("    #[test]\n");
        out.push_str("    fn rejects_bad_crc() {\n");

        out.push_str("        let mut frame = [");

        for (index, byte) in frame.iter().enumerate() {
            if index > 0 {
                out.push_str(", ");
            }

            out.push_str(&format!("0x{:02X}", byte));
        }

        out.push_str(
            r#"];

"#,
        );

        if model.checksum.checksum_start < frame.len() {
            out.push_str(&format!(
                "        frame[{}] ^= 0xFF;\n\n",
                model.checksum.checksum_start
            ));
        } else if frame.len() >= 1 {
            out.push_str("        frame[frame.len() - 1] ^= 0xFF;\n\n");
        }

        out.push_str(
            r#"        assert!(
            parse_frame(&frame).is_err(),
            "frame with corrupted checksum should be rejected"
        );
    }

"#,
        );

        // --------------------------------------------------------
        // Test: wrong length
        // --------------------------------------------------------

        out.push_str("    #[test]\n");
        out.push_str("    fn rejects_wrong_length() {\n");

        if let Some(length_offset) = model.framing.length_offset {
            // Length-framed protocol: mutate the length byte.
            out.push_str("        let mut frame: Vec<u8> = vec![");

            for (index, byte) in frame.iter().enumerate() {
                if index > 0 {
                    out.push_str(", ");
                }

                out.push_str(&format!("0x{:02X}", byte));
            }

            out.push_str("];\n\n");

            out.push_str(&format!(
                "        frame[{0}] = frame[{0}].wrapping_add(1u8);\n\n",
                length_offset
            ));

            out.push_str(
                r#"        assert!(
            parse_frame(&frame).is_err(),
            "frame with invalid length should be rejected"
        );
    }
"#,
            );
        } else if frame.len() > 1 {
            // Fixed-length protocol: remove one byte.
            out.push_str("        let frame: &[u8] = &[");

            for (index, byte) in frame[..frame.len() - 1].iter().enumerate() {
                if index > 0 {
                    out.push_str(", ");
                }

                out.push_str(&format!("0x{:02X}", byte));
            }

            out.push_str(
                r#"];

        assert!(
            parse_frame(frame).is_err(),
            "frame with invalid length should be rejected"
        );
    }
"#,
            );
        } else {
            out.push_str(
                r#"        let frame: &[u8] = &[];

        assert!(
            parse_frame(frame).is_err(),
            "frame with invalid length should be rejected"
        );
    }
"#,
            );
        }

        out.push_str("}\n");
    }

    out
}
