use crate::fields::FieldInterpretation;
use crate::model::ProtocolModel;

fn field_name(index: usize, field: &FieldInterpretation) -> String {
    match field {
        FieldInterpretation::Constant { .. } => {
            if index == 0 {
                "header".to_string()
            } else {
                format!("reserved_{}", index - 1)
            }
        }

        FieldInterpretation::CounterLike { .. } => {
            if index == 0 {
                "counter".to_string()
            } else {
                format!("counter_{}", index)
            }
        }

        _ => format!("field_{}", index),
    }
}

fn best_unique_multi_byte(
    model: &ProtocolModel,
) -> Option<&crate::fields::MultiByteInterpretation> {
    if model.multi_byte_fields.is_empty() {
        return None;
    }

    let best_score = model
        .multi_byte_fields
        .iter()
        .map(|field| field.score)
        .max()?;

    let mut best = model
        .multi_byte_fields
        .iter()
        .filter(|field| field.score == best_score);

    let first = best.next()?;

    if best.next().is_some() {
        return None;
    }

    Some(first)
}

fn multi_byte_type(kind: &str) -> Option<&'static str> {
    match kind {
        "U16LittleEndian" | "U16BigEndian" => Some("u16"),
        "U32LittleEndian" | "U32BigEndian" => Some("u32"),
        _ => None,
    }
}

fn multi_byte_expression(kind: &str, start: usize) -> Option<String> {
    match kind {
        "U16LittleEndian" => Some(format!(
            "u16::from_le_bytes([frame[{}], frame[{}]])",
            start,
            start + 1
        )),

        "U16BigEndian" => Some(format!(
            "u16::from_be_bytes([frame[{}], frame[{}]])",
            start,
            start + 1
        )),

        "U32LittleEndian" => Some(format!(
            "u32::from_le_bytes([frame[{}], frame[{}], frame[{}], frame[{}]])",
            start,
            start + 1,
            start + 2,
            start + 3
        )),

        "U32BigEndian" => Some(format!(
            "u32::from_be_bytes([frame[{}], frame[{}], frame[{}], frame[{}]])",
            start,
            start + 1,
            start + 2,
            start + 3
        )),

        _ => None,
    }
}

fn unique_field_name(base: String, used: &mut Vec<String>) -> String {
    if !used.contains(&base) {
        used.push(base.clone());
        return base;
    }

    let mut suffix = 2;

    loop {
        let candidate = format!("{}_{}", base, suffix);

        if !used.contains(&candidate) {
            used.push(candidate.clone());
            return candidate;
        }

        suffix += 1;
    }
}

pub fn generate_rust(model: &ProtocolModel, frames: &[Vec<u8>]) -> String {
    let mut out = String::new();

    out.push_str("// Generated by Babelfish\n");
    out.push_str("// WARNING: Review all ambiguous interpretations before production use.\n\n");

    // ------------------------------------------------------------
    // Determine unique multi-byte interpretation
    // ------------------------------------------------------------

    let unique_multi_byte = best_unique_multi_byte(model);

    // ------------------------------------------------------------
    // Packet struct
    // ------------------------------------------------------------

    out.push_str("#[derive(Debug)]\n");
    out.push_str("pub struct Packet {\n");

    let mut struct_names = Vec::new();

    for (index, field) in model.fields.iter().enumerate() {
        let position = model.checksum.coverage_start + index;

        // If a unique multi-byte interpretation starts here, generate
        // one typed field instead of generating its individual bytes.
        if let Some(multi) = unique_multi_byte {
            if multi.start == position {
                if let Some(rust_type) = multi_byte_type(&multi.kind) {
                    let base_name = format!("value_{}", multi.start);
                    let name = unique_field_name(base_name, &mut struct_names);

                    out.push_str(&format!("    pub {}: {},\n", name, rust_type));

                    continue;
                }
            }

            // Skip bytes consumed by a typed multi-byte field.
            if position > multi.start && position < multi.start + multi.width {
                continue;
            }
        }

        let name = unique_field_name(field_name(index, field), &mut struct_names);

        out.push_str(&format!("    pub {}: u8,\n", name));
    }

    out.push_str("}\n\n");

    // ------------------------------------------------------------
    // CRC8 implementation
    // ------------------------------------------------------------

    if model.checksum.algorithm == "CRC8" {
        out.push_str(
            r#"fn crc8(data: &[u8]) -> u8 {
    let mut crc = 0u8;

    for &byte in data {
        crc ^= byte;

        for _ in 0..8 {
            if crc & 0x80 != 0 {
                crc = (crc << 1) ^ 0x07;
            } else {
                crc <<= 1;
            }
        }
    }

    crc
}

"#,
        );
    }

    // ------------------------------------------------------------
    // CRC16/MODBUS implementation
    // ------------------------------------------------------------

    if model.checksum.algorithm == "CRC16/MODBUS" {
        out.push_str(
            r#"fn crc16_modbus(data: &[u8]) -> u16 {
    let mut crc: u16 = 0xFFFF;

    for &byte in data {
        crc ^= byte as u16;

        for _ in 0..8 {
            if crc & 1 != 0 {
                crc = (crc >> 1) ^ 0xA001;
            } else {
                crc >>= 1;
            }
        }
    }

    crc
}

"#,
        );
    }

    // ------------------------------------------------------------
    // Determine framing
    // ------------------------------------------------------------

    let has_prefix = model.framing.kind != "prefix []";

    // ------------------------------------------------------------
    // Parser
    // ------------------------------------------------------------

    out.push_str("pub fn parse_frame(frame: &[u8]) -> Result<Packet, &'static str> {\n");

    let required_length = model.checksum.checksum_end.max(model.checksum.coverage_end);

    out.push_str(&format!("    if frame.len() != {} {{\n", required_length));
    out.push_str("        return Err(\"invalid frame length\");\n");
    out.push_str("    }\n\n");

    // ------------------------------------------------------------
    // Framing
    // ------------------------------------------------------------

    out.push_str(&format!(
        "    // Detected framing: {}\n",
        model.framing.kind
    ));

    if model.framing.kind == "prefix [7E, 10]" {
        out.push_str(
            r#"    if frame[0] != 0x7E || frame[1] != 0x10 {
        return Err("invalid frame prefix");
    }

"#,
        );
    }

    // ------------------------------------------------------------
    // Checksum information
    // ------------------------------------------------------------

    out.push_str(&format!(
        "    // Detected checksum: {}\n",
        model.checksum.algorithm
    ));

    out.push_str(&format!(
        "    // Coverage: bytes[{}..{}]\n",
        model.checksum.coverage_start, model.checksum.coverage_end
    ));

    out.push_str(&format!(
        "    // Checksum: bytes[{}..{}]\n\n",
        model.checksum.checksum_start, model.checksum.checksum_end
    ));

    // ------------------------------------------------------------
    // CRC8 validation
    // ------------------------------------------------------------

    if model.checksum.algorithm == "CRC8" {
        out.push_str(&format!(
            "    let expected_crc = crc8(&frame[{}..{}]);\n",
            model.checksum.coverage_start, model.checksum.coverage_end
        ));

        out.push_str(&format!(
            "    if frame[{}] != expected_crc {{\n",
            model.checksum.checksum_start
        ));

        out.push_str("        return Err(\"CRC8 validation failed\");\n");
        out.push_str("    }\n\n");
    }

    // ------------------------------------------------------------
    // CRC16/MODBUS validation
    // ------------------------------------------------------------

    if model.checksum.algorithm == "CRC16/MODBUS" {
        let start = model.checksum.checksum_start;

        out.push_str(&format!(
            "    let expected_crc = crc16_modbus(&frame[{}..{}]);\n",
            model.checksum.coverage_start, model.checksum.coverage_end
        ));

        out.push_str(&format!(
            "    let actual_crc = u16::from_le_bytes([frame[{}], frame[{}]]);\n",
            start,
            start + 1
        ));

        out.push_str("    if actual_crc != expected_crc {\n");
        out.push_str("        return Err(\"CRC16/MODBUS validation failed\");\n");
        out.push_str("    }\n\n");
    }

    // ------------------------------------------------------------
    // Field extraction
    // ------------------------------------------------------------

    let mut generated_names = Vec::new();

    for (index, field) in model.fields.iter().enumerate() {
        let position = model.checksum.coverage_start + index;

        if let Some(multi) = unique_multi_byte {
            if multi.start == position {
                if let (Some(_rust_type), Some(expression)) = (
                    multi_byte_type(&multi.kind),
                    multi_byte_expression(&multi.kind, multi.start),
                ) {
                    let base_name = format!("value_{}", multi.start);
                    let name = unique_field_name(base_name, &mut generated_names);

                    out.push_str(&format!("    let {} = {};\n", name, expression));

                    continue;
                }
            }

            if position > multi.start && position < multi.start + multi.width {
                continue;
            }
        }

        let base_name = field_name(index, field);
        let name = unique_field_name(base_name, &mut generated_names);

        out.push_str(&format!("    let {} = frame[{}];\n", name, position));
    }

    // ------------------------------------------------------------
    // Return Packet
    // ------------------------------------------------------------

    out.push_str("\n    Ok(Packet {\n");

    for name in &generated_names {
        out.push_str(&format!("        {},\n", name));
    }

    out.push_str("    })\n");
    out.push_str("}\n");

    // ------------------------------------------------------------
    // Ambiguity information
    // ------------------------------------------------------------

    if unique_multi_byte.is_none() && model.multi_byte_fields.len() > 1 {
        out.push_str(
            r#"

// WARNING: Protocol interpretation is ambiguous.
//
// Babelfish found competing multi-byte interpretations
// with equal evidence. Do not select one without additional
// protocol evidence.
//
// Candidates:
"#,
        );

        for field in &model.multi_byte_fields {
            out.push_str(&format!(
                "//   bytes[{}..{}] -> {:?}, score {:.2}\n",
                field.start,
                field.start + field.width,
                field.kind,
                field.score
            ));
        }

        out.push_str(
            r#"//
// No multi-byte candidate was selected because
// the evidence does not uniquely determine one.
"#,
        );
    }

    // ------------------------------------------------------------
    // Generated parser tests
    // ------------------------------------------------------------

    if let Some(frame) = frames.first() {
        out.push_str(
            r#"

#[cfg(test)]
mod tests {
    use super::*;

"#,
        );

        // --------------------------------------------------------
        // Test 1: Real captured frame
        // --------------------------------------------------------

        out.push_str("    #[test]\n");
        out.push_str("    fn parses_real_frame() {\n");
        out.push_str("        let frame = [");

        for (index, byte) in frame.iter().enumerate() {
            if index > 0 {
                out.push_str(", ");
            }

            out.push_str(&format!("0x{:02X}", byte));
        }

        out.push_str(
            r#"];

        let packet = parse_frame(&frame)
            .expect("real captured frame should parse");

"#,
        );

        // Generate assertions that match the generated representation.
        let mut assertion_names = Vec::new();

        for (index, field) in model.fields.iter().enumerate() {
            let position = model.checksum.coverage_start + index;

            if let Some(multi) = unique_multi_byte {
                if multi.start == position {
                    if multi_byte_type(&multi.kind).is_some() {
                        let base_name = format!("value_{}", multi.start);
                        let name = unique_field_name(base_name, &mut assertion_names);

                        if multi.width == 2 && multi.start + 1 < frame.len() {
                            let expected = match multi.kind.as_str() {
                                "U16LittleEndian" => {
                                    u16::from_le_bytes([frame[multi.start], frame[multi.start + 1]])
                                }

                                "U16BigEndian" => {
                                    u16::from_be_bytes([frame[multi.start], frame[multi.start + 1]])
                                }

                                _ => 0,
                            };

                            out.push_str(&format!(
                                "        assert_eq!(packet.{}, 0x{:04X});\n",
                                name, expected
                            ));
                        } else if multi.width == 4 && multi.start + 3 < frame.len() {
                            let expected = match multi.kind.as_str() {
                                "U32LittleEndian" => u32::from_le_bytes([
                                    frame[multi.start],
                                    frame[multi.start + 1],
                                    frame[multi.start + 2],
                                    frame[multi.start + 3],
                                ]),

                                "U32BigEndian" => u32::from_be_bytes([
                                    frame[multi.start],
                                    frame[multi.start + 1],
                                    frame[multi.start + 2],
                                    frame[multi.start + 3],
                                ]),

                                _ => 0,
                            };

                            out.push_str(&format!(
                                "        assert_eq!(packet.{}, 0x{:08X});\n",
                                name, expected
                            ));
                        }

                        continue;
                    }
                }

                if position > multi.start && position < multi.start + multi.width {
                    continue;
                }
            }

            let base_name = field_name(index, field);
            let name = unique_field_name(base_name, &mut assertion_names);

            if position < frame.len() {
                out.push_str(&format!(
                    "        assert_eq!(packet.{}, 0x{:02X});\n",
                    name, frame[position]
                ));
            }
        }

        out.push_str(
            r#"    }

"#,
        );

        // --------------------------------------------------------
        // Test 2: Bad checksum
        // --------------------------------------------------------

        out.push_str(
            r#"    #[test]
    fn rejects_bad_crc() {
        let frame = [
"#,
        );

        for (index, byte) in frame.iter().enumerate() {
            if index > 0 {
                out.push_str(", ");
            }

            let value =
                if index >= model.checksum.checksum_start && index < model.checksum.checksum_end {
                    byte.wrapping_add(1)
                } else {
                    *byte
                };

            out.push_str(&format!("0x{:02X}", value));
        }

        out.push_str(
            r#"
        ];

        assert!(
            parse_frame(&frame).is_err(),
            "frame with corrupted checksum should be rejected"
        );
    }

"#,
        );

        // --------------------------------------------------------
        // Test 3: Bad prefix
        // --------------------------------------------------------

        if has_prefix {
            out.push_str(
                r#"    #[test]
    fn rejects_bad_prefix() {
        let frame = [
"#,
            );

            for (index, byte) in frame.iter().enumerate() {
                if index > 0 {
                    out.push_str(", ");
                }

                let value = if index == 0 { byte ^ 0xFF } else { *byte };

                out.push_str(&format!("0x{:02X}", value));
            }

            out.push_str(
                r#"
        ];

        assert!(
            parse_frame(&frame).is_err(),
            "frame with invalid prefix should be rejected"
        );
    }

"#,
            );
        }

        // --------------------------------------------------------
        // Test 4: Wrong length
        // --------------------------------------------------------

        out.push_str(
            r#"    #[test]
    fn rejects_wrong_length() {
        let frame = [
"#,
        );

        for (index, byte) in frame.iter().take(frame.len().saturating_sub(1)).enumerate() {
            if index > 0 {
                out.push_str(", ");
            }

            out.push_str(&format!("0x{:02X}", byte));
        }

        out.push_str(
            r#"
        ];

        assert!(
            parse_frame(&frame).is_err(),
            "frame with invalid length should be rejected"
        );
    }
}
"#,
        );
    }

    out
}
